import localFont from "next/font/local";
import "../styles/globals.css";

// const geistSans = localFont({
//   src: "./fonts/GeistVF.woff",
//   variable: "--font-geist-sans",
//   weight: "100 900",
// });
// const geistMono = localFont({
//   src: "./fonts/GeistMonoVF.woff",
//   variable: "--font-geist-mono",
//   weight: "100 900",
// });

export const metadata = {
  title: "Create Next App", 
  description: "Generated by create next app",
};

export default function RootLayout({ Component, pageProps,children }) {
  return (
      <>
        <Component {...pageProps} />
        </>
  );
}


// import './styles/globals.css';

// export default function MyApp({ Component, pageProps }) {
//   return (
//     <div>
//       <header>
//         <nav>
//           <a href="/">Home</a> | <a href="/cart">Cart</a> | <a href="/about">About</a>
//         </nav>
//       </header>
//       <main>
//         <Component {...pageProps} />
//       </main>
//     </div>
//   );
// }
